### ISSUE TITLE
开设实用的工具类网站分区

### ISSUE THREAD

**Issue by trace1729** [storage-db/ToolDiy#42]
考虑为网页增设一个分区吗？

**Comment by SakurajimaMaii** [comment]
可以，该分区主要用来做什么

**Comment by trace1729** [comment]
收录一些实用的工具类网站吧，类似 [godbolt](https://godbolt.org//), [latex live][https://www.latexlive.com/##] 这种。

**Comment by SakurajimaMaii** [comment]
没问题，在有该类文章被提交pr请求后我们会专门开设该分区

**Comment by trace1729** [comment]
cool！
